# Generated by Django 5.1.3 on 2025-01-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftable',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='stafftable',
            name='DEPARTMENTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmenttable'),
        ),
        migrations.AddField(
            model_name='stafftable',
            name='sem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
