# Generated by Django 5.1.3 on 2025-01-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_stafftable_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabletable',
            name='sem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
