# Generated by Django 5.1.3 on 2024-12-06 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendancetable_complainttable_coursetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable'),
        ),
        migrations.AddField(
            model_name='teachertable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable'),
        ),
    ]
