# Generated by Django 5.1.3 on 2025-01-11 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_timetabletable_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassNo', models.CharField(blank=True, max_length=100, null=True)),
                ('DEPARTMENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmenttable')),
            ],
        ),
    ]
