# Generated by Django 5.1.3 on 2024-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_studenttable_loginid_teachertable_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
