# Generated by Django 5.1.3 on 2024-12-11 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notification_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetable',
            old_name='subject',
            new_name='CourseName',
        ),
        migrations.RenameField(
            model_name='departmenttable',
            old_name='subject',
            new_name='Dept_Name',
        ),
        migrations.RemoveField(
            model_name='departmenttable',
            name='TEACHERID',
        ),
        migrations.RemoveField(
            model_name='teachertable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teachertable',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable'),
        ),
        migrations.AddField(
            model_name='coursetable',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmenttable'),
        ),
        migrations.DeleteModel(
            name='SubjectTable',
        ),
        migrations.AddField(
            model_name='teachertable',
            name='DEPARTMENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmenttable'),
        ),
    ]
