# Generated by Django 5.1.3 on 2025-01-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_classtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabletable',
            name='SUBJECTID',
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='CLASS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.classtable'),
        ),
    ]
