# Generated by Django 5.1.3 on 2024-12-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_subject_coursetable_coursename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='department',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='DEPARTMENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmenttable'),
        ),
    ]
