# Generated by Django 5.1.3 on 2025-01-12 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_timetabletable_subjectid_timetabletable_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabletable',
            name='Date',
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='Day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subjecttable'),
        ),
    ]
