# Generated by Django 5.1.3 on 2025-01-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_timetabletable_date_timetabletable_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('CLASS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.classtable')),
                ('slot_10_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_10_11', to='myapp.subjecttable')),
                ('slot_11_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_11_12', to='myapp.subjecttable')),
                ('slot_1_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_1_2', to='myapp.subjecttable')),
                ('slot_2_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_2_3', to='myapp.subjecttable')),
                ('slot_3_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_3_4', to='myapp.subjecttable')),
                ('slot_9_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_9_10', to='myapp.subjecttable')),
            ],
        ),
    ]
