# Generated by Django 5.1.3 on 2024-12-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_studenttable_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancetable',
            old_name='LOGINID',
            new_name='StudentID',
        ),
        migrations.RemoveField(
            model_name='attendancetable',
            name='rollno',
        ),
        migrations.RemoveField(
            model_name='dutyrequesttable',
            name='TEACHERID',
        ),
        migrations.AddField(
            model_name='dutyrequesttable',
            name='STUDENTID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studenttable'),
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('COURSE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.coursetable')),
            ],
        ),
        migrations.AddField(
            model_name='teachertable',
            name='SUBJECT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subjecttable'),
        ),
    ]
