# Generated by Django 5.1.3 on 2024-12-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_loginid_attendancetable_studentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttable',
            name='COURSE',
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='DEPARTMENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.departmenttable'),
        ),
    ]
