# Generated by Django 5.1.3 on 2025-01-25 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_timetable1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='DEPARTMENT',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='CLASS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.classtable'),
        ),
    ]
