# Generated by Django 5.1.3 on 2025-01-25 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_studenttable_department_studenttable_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetable',
            name='StudentID',
        ),
        migrations.RemoveField(
            model_name='attendancetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='attendancetable',
            name='hour',
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='Attendance',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='Date',
            field=models.DateField(default='2025-01-12', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='Period',
            field=models.CharField(blank=True, choices=[('slot_9_10', 'slot_9_10'), ('slot_10_11', 'slot_10_11'), ('slot_11_12', 'slot_11_12'), ('slot_1_2', 'slot_1_2 '), ('slot_2_3', 'slot_2_3 '), ('slot_3_4', 'slot_3_4')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='STUDENT_ID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.studenttable'),
            preserve_default=False,
        ),
    ]
