# Generated by Django 5.1.3 on 2024-12-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_subjecttable_course_subjecttable_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainttable',
            name='report',
        ),
    ]
