# Generated by Django 5.1.3 on 2024-12-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_complainttable_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
