# Generated by Django 5.1.3 on 2024-12-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_complainttable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='StudentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.studenttable'),
        ),
    ]
