# Generated by Django 5.1.3 on 2025-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_studenttable_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dutyrequesttable',
            old_name='department',
            new_name='slot',
        ),
        migrations.AddField(
            model_name='dutyrequesttable',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-02-25'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='image',
            field=models.FileField(default='10-02-2025', upload_to=''),
            preserve_default=False,
        ),
    ]
