# Generated by Django 5.1.3 on 2025-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_department_dutyrequesttable_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyrequesttable',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
